version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookstore
    volumes:
      - ./bookstore_data:/var/lib/postgresql/data
    ports:
      - 5440:5432